/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dta.system;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import static javax.swing.JFrame.setDefaultLookAndFeelDecorated;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ayoma
 */



public class AccountsManagement extends javax.swing.JFrame {
selectData selectD=new selectData();
dbInsert saveData=new dbInsert();
comboFill fillAccounts=new comboFill();
DefaultTableModel model;
    /**
     * Creates new form AccountsManagement
     */
    public AccountsManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        comboCreditAccount = new javax.swing.JComboBox<>();
        comboCreditDepartment = new javax.swing.JComboBox<>();
        pnpContent = new javax.swing.JPanel();
        pnpNewGL = new javax.swing.JPanel();
        pnpChartsOfAccounts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        pnpDepartment = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDepartmentName = new javax.swing.JTextField();
        txtDepartDescription = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartments = new javax.swing.JTable();
        pnpEntry = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboDebitAccount = new javax.swing.JComboBox<>();
        txtDebitAmount = new javax.swing.JTextField();
        comboDebitDepartment = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCreditAmount = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtVoucherNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCredits = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        lblCOA = new javax.swing.JLabel();
        lblCOA1 = new javax.swing.JLabel();
        lblCOA2 = new javax.swing.JLabel();

        lblCode.setText(" ");

        comboCreditAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboCreditDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);

        pnpContent.setBackground(new java.awt.Color(255, 255, 255));
        pnpContent.setOpaque(false);
        pnpContent.setLayout(new java.awt.CardLayout());

        pnpNewGL.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnpNewGLLayout = new javax.swing.GroupLayout(pnpNewGL);
        pnpNewGL.setLayout(pnpNewGLLayout);
        pnpNewGLLayout.setHorizontalGroup(
            pnpNewGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        pnpNewGLLayout.setVerticalGroup(
            pnpNewGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        pnpContent.add(pnpNewGL, "card2");

        pnpChartsOfAccounts.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHARTS OF ACCOUNTS");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Type");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Code");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Account Name");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Description");

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Account Type-", "Assets", "Liabilities", "Equity", "Revenue", "Expenses" }));
        comboType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));
        comboType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTypeItemStateChanged(evt);
            }
        });

        txtName.setText(" ");
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtCode.setText(" ");
        txtCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtDescription.setText(" ");
        txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("IsActive");

        javax.swing.GroupLayout pnpChartsOfAccountsLayout = new javax.swing.GroupLayout(pnpChartsOfAccounts);
        pnpChartsOfAccounts.setLayout(pnpChartsOfAccountsLayout);
        pnpChartsOfAccountsLayout.setHorizontalGroup(
            pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                        .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(162, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnpChartsOfAccountsLayout.setVerticalGroup(
            pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpChartsOfAccountsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pnpContent.add(pnpChartsOfAccounts, "card3");

        pnpDepartment.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPARTMENT");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Department Name");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Description");

        txtDepartmentName.setText(" ");
        txtDepartmentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtDepartDescription.setText(" ");
        txtDepartDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));
        txtDepartDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartDescriptionActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDepartments);

        javax.swing.GroupLayout pnpDepartmentLayout = new javax.swing.GroupLayout(pnpDepartment);
        pnpDepartment.setLayout(pnpDepartmentLayout);
        pnpDepartmentLayout.setHorizontalGroup(
            pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpDepartmentLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnpDepartmentLayout.createSequentialGroup()
                        .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDepartmentName, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(txtDepartDescription)))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnpDepartmentLayout.setVerticalGroup(
            pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpDepartmentLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDepartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );

        pnpContent.add(pnpDepartment, "card4");

        pnpEntry.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADJUSTING ENTRY");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Credit Information");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 1, new java.awt.Color(51, 204, 255)));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Account Type");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Credit Amount");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Department");

        comboDebitAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDebitAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtDebitAmount.setText(" ");
        txtDebitAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        comboDebitDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDebitDepartment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Debit Information");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 1, new java.awt.Color(51, 204, 255)));

        jLabel16.setText("Debit Amount");

        txtCreditAmount.setText(" ");
        txtCreditAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Voucher No.");

        txtVoucherNo.setText(" ");
        txtVoucherNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Date");

        jDateChooser1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setOpaque(false);

        tblCredits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Head", "Amount", "Department"
            }
        ));
        tblCredits.setOpaque(false);
        tblCredits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCreditsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCredits);

        jButton3.setText("Add Debit Row");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        rSMaterialButtonCircle1.setText("submit");
        rSMaterialButtonCircle1.setFocusPainted(false);

        javax.swing.GroupLayout pnpEntryLayout = new javax.swing.GroupLayout(pnpEntry);
        pnpEntry.setLayout(pnpEntryLayout);
        pnpEntryLayout.setHorizontalGroup(
            pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpEntryLayout.createSequentialGroup()
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDebitAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboDebitDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(68, 68, 68))
            .addGroup(pnpEntryLayout.createSequentialGroup()
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpEntryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpEntryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rSMaterialButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnpEntryLayout.setVerticalGroup(
            pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpEntryLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel19)
                .addGap(0, 0, 0)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnpEntryLayout.createSequentialGroup()
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(5, 5, 5)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDebitAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDebitDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnpEntryLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addComponent(jLabel14)
                .addGap(0, 0, 0)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel16)
                    .addComponent(txtCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSMaterialButtonCircle1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pnpContent.add(pnpEntry, "card5");

        lblCOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/system/icons/charts.png"))); // NOI18N
        lblCOA.setText("Charts Of Accounts");
        lblCOA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCOAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCOAMouseExited(evt);
            }
        });

        lblCOA1.setBackground(new java.awt.Color(0, 204, 204));
        lblCOA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/system/icons/department.png"))); // NOI18N
        lblCOA1.setText("Department");
        lblCOA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOA1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCOA1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCOA1MouseExited(evt);
            }
        });

        lblCOA2.setBackground(new java.awt.Color(51, 204, 255));
        lblCOA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/system/icons/adjustacc.png"))); // NOI18N
        lblCOA2.setText("Adjust Entry");
        lblCOA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOA2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCOA2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCOA2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCOA, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCOA1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCOA2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnpContent, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnpContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCOA2)
                        .addGap(18, 18, 18)
                        .addComponent(lblCOA1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCOA)
                        .addContainerGap(317, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCOAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOAMouseClicked
        pnpContent.removeAll();
        pnpContent.repaint();
        pnpContent.revalidate();
        pnpContent.add(pnpChartsOfAccounts);

// TODO add your handling code here:
    }//GEN-LAST:event_lblCOAMouseClicked

    private void comboTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTypeItemStateChanged
        String accountType = comboType.getSelectedItem().toString();
        int mainCode;
        int mainorCode;

        switch (accountType) {
            case "Assets":
                lblCode.setText("1000");
                selectD.loadAcctType(txtCode, comboType,lblCode);
                
                mainCode = Integer.parseInt(lblCode.getText().trim());
                mainorCode = Integer.parseInt(txtCode.getText().trim());
                mainorCode = mainorCode + mainCode;
                txtCode.setText(String.valueOf(mainorCode));

                break;
            case "Liabilities":
                lblCode.setText("2000");
                selectD.loadAcctType(txtCode, comboType,lblCode);
                
                mainCode = Integer.parseInt(lblCode.getText().trim());
                mainorCode = Integer.parseInt(txtCode.getText().trim());
                mainorCode = mainorCode + mainCode;
                txtCode.setText(String.valueOf(mainorCode));

                break;
            case "Equity":
                lblCode.setText("3000");
                selectD.loadAcctType(txtCode, comboType,lblCode);

                mainCode = Integer.parseInt(lblCode.getText().trim());
                mainorCode = Integer.parseInt(txtCode.getText().trim());
                mainorCode = mainorCode + mainCode;
                txtCode.setText(String.valueOf(mainorCode));

                break;
            case "Revenue":
                lblCode.setText("4000");
                selectD.loadAcctType(txtCode, comboType,lblCode);

                mainCode = Integer.parseInt(lblCode.getText().trim());
                mainorCode = Integer.parseInt(txtCode.getText().trim());
                mainorCode = mainorCode + mainCode;
                txtCode.setText(String.valueOf(mainorCode));

                break;
            case "Expenses":
                lblCode.setText("5000");
                selectD.loadAcctType(txtCode, comboType,lblCode);

                mainCode = Integer.parseInt(lblCode.getText().trim());
                mainorCode = Integer.parseInt(txtCode.getText().trim());
                mainorCode = mainorCode + mainCode;
                txtCode.setText(String.valueOf(mainorCode));

                break;
            case "-Select Account Type-": 
                lblCode.setText("");
                break;
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveData.SaveGLAccounts(txtName, txtCode, txtDescription, comboType);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblCOA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA1MouseClicked
        pnpContent.removeAll();
        pnpContent.repaint();
        pnpContent.revalidate();
        pnpContent.add(pnpDepartment);
        String sql = "SELECT `Serial_No`, `Department_Name`, `Description` FROM `department`";
        saveData.output(tblDepartments, sql);

 
    }//GEN-LAST:event_lblCOA1MouseClicked

    private void txtDepartDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartDescriptionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveData.SaveDepartments(txtDepartmentName, txtDepartDescription,tblDepartments);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblCOA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA2MouseClicked
        pnpContent.removeAll();
        pnpContent.repaint();
        pnpContent.revalidate();
        pnpContent.add(pnpEntry);
        
        fillAccounts.FillCombobox(comboDebitAccount, "glaccounts", "Account_Name", "Status", "1");
        fillAccounts.FillCombobox(comboCreditAccount, "glaccounts", "Account_Name", "Status", "1");
        
        fillAccounts.FillCombobox(comboDebitDepartment, "department", "Department_Name", "Status", "1");
        fillAccounts.FillCombobox(comboCreditDepartment, "department", "Department_Name", "Status", "1");
        
        


// TODO add your handling code here:
    }//GEN-LAST:event_lblCOA2MouseClicked

    private void lblCOA2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA2MouseEntered
        lblCOA2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCOA2.setBackground(Color.getHSBColor(51, 153, 255));
        lblCOA2.setOpaque(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA2MouseEntered

    private void lblCOA1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA1MouseEntered
        lblCOA1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCOA1.setBackground(Color.getHSBColor(51, 204, 255));
        lblCOA1.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA1MouseEntered

    private void lblCOAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOAMouseEntered
        lblCOA.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCOA.setBackground(Color.getHSBColor(51, 204, 255));
        lblCOA.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOAMouseEntered

    private void lblCOA2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA2MouseExited

        lblCOA2.setBackground(Color.getHSBColor(240, 240, 240));
        lblCOA2.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA2MouseExited

    private void lblCOAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOAMouseExited
        lblCOA.setBackground(Color.getHSBColor(240, 240, 240));
        lblCOA.setOpaque(false);         // TODO add your handling code here:
    }//GEN-LAST:event_lblCOAMouseExited

    private void lblCOA1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA1MouseExited
        lblCOA1.setBackground(Color.getHSBColor(240, 240, 240));
        lblCOA1.setOpaque(false);         // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA1MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // String[] categories = {"Category 1", "Category 2", "Category 3"};
        //JComboBox<String> comboBox = new JComboBox<>(categories);
        model = (DefaultTableModel) tblCredits.getModel();
        tblCredits.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(comboCreditAccount));
        tblCredits.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(comboCreditDepartment));
        model.addRow(new Object[]{"", txtCreditAmount.getText().trim(), ""});// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tblCreditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCreditsMouseClicked
        model.removeRow(tblCredits.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_tblCreditsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
          /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
              
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            com.jtattoo.plaf.mcwin.McWinLookAndFeel.setTheme("Modern", "", "");
            //UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
            // UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

            //UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println(e);
        }  
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setDefaultLookAndFeelDecorated(false);
                new AccountsManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCreditAccount;
    private javax.swing.JComboBox<String> comboCreditDepartment;
    private javax.swing.JComboBox<String> comboDebitAccount;
    private javax.swing.JComboBox<String> comboDebitDepartment;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCOA;
    private javax.swing.JLabel lblCOA1;
    private javax.swing.JLabel lblCOA2;
    private javax.swing.JLabel lblCode;
    private javax.swing.JPanel pnpChartsOfAccounts;
    private javax.swing.JPanel pnpContent;
    private javax.swing.JPanel pnpDepartment;
    private javax.swing.JPanel pnpEntry;
    private javax.swing.JPanel pnpNewGL;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private javax.swing.JTable tblCredits;
    private javax.swing.JTable tblDepartments;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCreditAmount;
    private javax.swing.JTextField txtDebitAmount;
    private javax.swing.JTextField txtDepartDescription;
    private javax.swing.JTextField txtDepartmentName;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtVoucherNo;
    // End of variables declaration//GEN-END:variables
}
