/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dta.system;

/**
 *
 * @author Ayoma
 */

import java.awt.Color;
import java.awt.Cursor;

public class accounts extends javax.swing.JPanel {

    selectData selectD = new selectData();
    dbInsert saveData = new dbInsert();
    comboFill fillAccounts = new comboFill();

    /**
     * Creates new form accounts
     */
    public accounts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        pnpContent = new javax.swing.JPanel();
        pnpEntry = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboDebitAccount = new javax.swing.JComboBox<>();
        txtDebitAmount = new javax.swing.JTextField();
        comboDebitDepartment = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboCreditDepartment = new javax.swing.JComboBox<>();
        txtCreditAmount = new javax.swing.JTextField();
        comboCreditAccount = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtVoucherNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnpNewGL = new javax.swing.JPanel();
        pnpChartsOfAccounts = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboType = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        pnpDepartment = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDepartmentName = new javax.swing.JTextField();
        txtDepartDescription = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDepartments = new javax.swing.JTable();
        lblCOA2 = new javax.swing.JLabel();
        lblCOA1 = new javax.swing.JLabel();
        lblCOA = new javax.swing.JLabel();

        lblCode.setText(" ");

        setOpaque(false);

        pnpContent.setBackground(new java.awt.Color(255, 255, 255));
        pnpContent.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(51, 204, 255)));
        pnpContent.setOpaque(false);
        pnpContent.setLayout(new java.awt.CardLayout());

        pnpEntry.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ADJUSTING ENTRY");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Debit");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 1, new java.awt.Color(51, 204, 255)));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Account Type");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Debit Amount");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Department");

        comboDebitAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDebitAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtDebitAmount.setText(" ");
        txtDebitAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        comboDebitDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDebitDepartment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Credit");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 1, new java.awt.Color(51, 204, 255)));

        jLabel15.setText("Account Type");

        jLabel16.setText("Credit Amount");

        jLabel17.setText("Department");

        comboCreditDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCreditDepartment.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtCreditAmount.setText(" ");
        txtCreditAmount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        comboCreditAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCreditAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Voucher No.");

        txtVoucherNo.setText(" ");
        txtVoucherNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Date");

        javax.swing.GroupLayout pnpEntryLayout = new javax.swing.GroupLayout(pnpEntry);
        pnpEntry.setLayout(pnpEntryLayout);
        pnpEntryLayout.setHorizontalGroup(
            pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnpEntryLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnpEntryLayout.createSequentialGroup()
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDebitAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboDebitAccount, 0, 141, Short.MAX_VALUE)
                            .addComponent(comboDebitDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnpEntryLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnpEntryLayout.createSequentialGroup()
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCreditAccount, 0, 172, Short.MAX_VALUE)
                            .addComponent(txtCreditAmount)
                            .addComponent(comboCreditDepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        pnpEntryLayout.setVerticalGroup(
            pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpEntryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnpEntryLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(comboCreditAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtCreditAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(comboCreditDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnpEntryLayout.createSequentialGroup()
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnpEntryLayout.createSequentialGroup()
                                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtVoucherNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(comboDebitAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtDebitAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnpEntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(comboDebitDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(464, Short.MAX_VALUE))
        );

        pnpContent.add(pnpEntry, "card5");

        pnpNewGL.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnpNewGLLayout = new javax.swing.GroupLayout(pnpNewGL);
        pnpNewGL.setLayout(pnpNewGLLayout);
        pnpNewGLLayout.setHorizontalGroup(
            pnpNewGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1110, Short.MAX_VALUE)
        );
        pnpNewGLLayout.setVerticalGroup(
            pnpNewGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        pnpContent.add(pnpNewGL, "card2");

        pnpChartsOfAccounts.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHARTS OF ACCOUNTS");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Type");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Code");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Account Name");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Description");

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Account Type-", "Assets", "Liabilities", "Equity", "Revenue", "Expenses" }));
        comboType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));
        comboType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTypeItemStateChanged(evt);
            }
        });

        txtName.setText(" ");
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtCode.setText(" ");
        txtCode.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtDescription.setText(" ");
        txtDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("IsActive");

        javax.swing.GroupLayout pnpChartsOfAccountsLayout = new javax.swing.GroupLayout(pnpChartsOfAccounts);
        pnpChartsOfAccounts.setLayout(pnpChartsOfAccountsLayout);
        pnpChartsOfAccountsLayout.setHorizontalGroup(
            pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                .addContainerGap(316, Short.MAX_VALUE)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                        .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(315, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnpChartsOfAccountsLayout.setVerticalGroup(
            pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnpChartsOfAccountsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnpChartsOfAccountsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpChartsOfAccountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pnpContent.add(pnpChartsOfAccounts, "card3");

        pnpDepartment.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPARTMENT");
        jLabel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Department Name");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Description");

        txtDepartmentName.setText(" ");
        txtDepartmentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));

        txtDepartDescription.setText(" ");
        txtDepartDescription.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 204, 255)));
        txtDepartDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepartDescriptionActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblDepartments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDepartments);

        javax.swing.GroupLayout pnpDepartmentLayout = new javax.swing.GroupLayout(pnpDepartment);
        pnpDepartment.setLayout(pnpDepartmentLayout);
        pnpDepartmentLayout.setHorizontalGroup(
            pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpDepartmentLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnpDepartmentLayout.createSequentialGroup()
                        .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDepartmentName, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(txtDepartDescription)))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnpDepartmentLayout.setVerticalGroup(
            pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnpDepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnpDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDepartDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE))
        );

        pnpContent.add(pnpDepartment, "card4");

        lblCOA2.setBackground(new java.awt.Color(51, 204, 255));
        lblCOA2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCOA2.setForeground(new java.awt.Color(51, 204, 255));
        lblCOA2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/system/icons/adjustacc.png"))); // NOI18N
        lblCOA2.setText("Adjust Entry");
        lblCOA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOA2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCOA2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCOA2MouseExited(evt);
            }
        });

        lblCOA1.setBackground(new java.awt.Color(51, 204, 255));
        lblCOA1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCOA1.setForeground(new java.awt.Color(51, 204, 255));
        lblCOA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/system/icons/department.png"))); // NOI18N
        lblCOA1.setText("Department");
        lblCOA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOA1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCOA1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCOA1MouseExited(evt);
            }
        });

        lblCOA.setBackground(new java.awt.Color(51, 204, 255));
        lblCOA.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblCOA.setForeground(new java.awt.Color(51, 204, 255));
        lblCOA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dta/system/icons/charts.png"))); // NOI18N
        lblCOA.setText("Charts Of Accounts");
        lblCOA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCOAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCOAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCOAMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(lblCOA2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblCOA1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCOA)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnpContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCOA2)
                    .addComponent(lblCOA1)
                    .addComponent(lblCOA))
                .addContainerGap(674, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(pnpContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTypeItemStateChanged
        String accountType = comboType.getSelectedItem().toString();
        int mainCode;
        int mainorCode;

        switch (accountType) {
            case "Assets":
            lblCode.setText("1000");
            selectD.loadAcctType(txtCode, comboType,lblCode);

            mainCode = Integer.parseInt(lblCode.getText().trim());
            mainorCode = Integer.parseInt(txtCode.getText().trim());
            mainorCode = mainorCode + mainCode;
            txtCode.setText(String.valueOf(mainorCode));

            break;
            case "Liabilities":
            lblCode.setText("2000");
            selectD.loadAcctType(txtCode, comboType,lblCode);

            mainCode = Integer.parseInt(lblCode.getText().trim());
            mainorCode = Integer.parseInt(txtCode.getText().trim());
            mainorCode = mainorCode + mainCode;
            txtCode.setText(String.valueOf(mainorCode));

            break;
            case "Equity":
            lblCode.setText("3000");
            selectD.loadAcctType(txtCode, comboType,lblCode);

            mainCode = Integer.parseInt(lblCode.getText().trim());
            mainorCode = Integer.parseInt(txtCode.getText().trim());
            mainorCode = mainorCode + mainCode;
            txtCode.setText(String.valueOf(mainorCode));

            break;
            case "Revenue":
            lblCode.setText("4000");
            selectD.loadAcctType(txtCode, comboType,lblCode);

            mainCode = Integer.parseInt(lblCode.getText().trim());
            mainorCode = Integer.parseInt(txtCode.getText().trim());
            mainorCode = mainorCode + mainCode;
            txtCode.setText(String.valueOf(mainorCode));

            break;
            case "Expenses":
            lblCode.setText("5000");
            selectD.loadAcctType(txtCode, comboType,lblCode);

            mainCode = Integer.parseInt(lblCode.getText().trim());
            mainorCode = Integer.parseInt(txtCode.getText().trim());
            mainorCode = mainorCode + mainCode;
            txtCode.setText(String.valueOf(mainorCode));

            break;
            case "-Select Account Type-":
            lblCode.setText("");
            break;

        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboTypeItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        saveData.SaveGLAccounts(txtName, txtCode, txtDescription, comboType);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDepartDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepartDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepartDescriptionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveData.SaveDepartments(txtDepartmentName, txtDepartDescription,tblDepartments);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lblCOA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA2MouseClicked
        pnpContent.removeAll();
        pnpContent.repaint();
        pnpContent.revalidate();
        pnpContent.add(pnpEntry);

        fillAccounts.FillCombobox(comboDebitAccount, "glaccounts", "Account_Name", "Status", "1");
        fillAccounts.FillCombobox(comboCreditAccount, "glaccounts", "Account_Name", "Status", "1");

        fillAccounts.FillCombobox(comboDebitDepartment, "department", "Department_Name", "Status", "1");
        fillAccounts.FillCombobox(comboCreditDepartment, "department", "Department_Name", "Status", "1");

        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA2MouseClicked

    private void lblCOA2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA2MouseEntered
        lblCOA2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCOA2.setBackground(Color.getHSBColor(51, 153, 255));
        lblCOA2.setOpaque(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA2MouseEntered

    private void lblCOA2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA2MouseExited

        lblCOA2.setBackground(Color.getHSBColor(240, 240, 240));
        lblCOA2.setOpaque(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA2MouseExited

    private void lblCOA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA1MouseClicked
        pnpContent.removeAll();
        pnpContent.repaint();
        pnpContent.revalidate();
        pnpContent.add(pnpDepartment);
        String sql = "SELECT `Serial_No`, `Department_Name`, `Description` FROM `department`";
        saveData.output(tblDepartments, sql);

    }//GEN-LAST:event_lblCOA1MouseClicked

    private void lblCOA1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA1MouseEntered
        lblCOA1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCOA1.setBackground(Color.getHSBColor(51, 153, 255));
        lblCOA1.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA1MouseEntered

    private void lblCOA1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOA1MouseExited
        lblCOA1.setBackground(Color.getHSBColor(240, 240, 240));
        lblCOA1.setOpaque(false);         // TODO add your handling code here:
    }//GEN-LAST:event_lblCOA1MouseExited

    private void lblCOAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOAMouseClicked
        pnpContent.removeAll();
        pnpContent.repaint();
        pnpContent.revalidate();
        pnpContent.add(pnpChartsOfAccounts);

        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOAMouseClicked

    private void lblCOAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOAMouseEntered
        lblCOA.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCOA.setBackground(Color.getHSBColor(51, 153, 255));
        lblCOA.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lblCOAMouseEntered

    private void lblCOAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCOAMouseExited
        lblCOA.setBackground(Color.getHSBColor(240, 240, 240));
        lblCOA.setOpaque(false);         // TODO add your handling code here:
    }//GEN-LAST:event_lblCOAMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboCreditAccount;
    private javax.swing.JComboBox<String> comboCreditDepartment;
    private javax.swing.JComboBox<String> comboDebitAccount;
    private javax.swing.JComboBox<String> comboDebitDepartment;
    private javax.swing.JComboBox<String> comboType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCOA;
    private javax.swing.JLabel lblCOA1;
    private javax.swing.JLabel lblCOA2;
    private javax.swing.JLabel lblCode;
    private javax.swing.JPanel pnpChartsOfAccounts;
    private javax.swing.JPanel pnpContent;
    private javax.swing.JPanel pnpDepartment;
    private javax.swing.JPanel pnpEntry;
    private javax.swing.JPanel pnpNewGL;
    private javax.swing.JTable tblDepartments;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCreditAmount;
    private javax.swing.JTextField txtDebitAmount;
    private javax.swing.JTextField txtDepartDescription;
    private javax.swing.JTextField txtDepartmentName;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtVoucherNo;
    // End of variables declaration//GEN-END:variables
}
